version: '3'
services:
  nginx:
    image: nginx:1.25.1
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      # для храннеия сертификата
      #- ./certbot/www:/var/www/certbot/:ro 
      #- ./certbot/conf/:/etc/nginx/ssl/:ro
      # для статических файлов сайта
      - ./HTML/index.html:/usr/share/nginx/html/index.html:ro
      - ./HTML/png:/usr/share/nginx/html/png:ro
      - ./HTML/css:/usr/share/nginx/html/css:ro
      - ./HTML/js:/usr/share/nginx/html/js:ro
    ports:
      - 80:80
      - 443:443
